i changed up and almost got it. i have two more
[100%] Linking CXX executable sep_engine
/usr/sbin/ld: /sep/lib/libcycles_scene.a(image_vdb.cpp.o): undefined reference to symbol '_ZN7openvdb5v11_02io12getHalfFloatERSt8ios_base'
/usr/sbin/ld: /usr/lib64/libopenvdb.so.11.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

pls use the others that re now fixed to help get these last two straightened out.